[Icon Theme]
Name=Quail Icons
Name[af]=Quail
Name[an]=Quail
Name[ar]=جنوم
Name[as]=Quail
Name[ast]=Quail
Name[az]=Quail
Name[be]=Quail
Name[be@latin]=Quail
Name[bg]=Quail
Name[bn]=Quail
Name[bn_IN]=Quail
Name[br]=Quail
Name[bs]=Quail
Name[ca]=Quail
Name[ca@valencia]=Quail
Name[crh]=Quail
Name[cs]=Quail
Name[csb]=Quail
Name[cy]=Quail
Name[da]=Gnome
Name[de]=Quail
Name[dz]=ཇི་ནོམ།
Name[el]=Quail
Name[en@shaw]=·𐑜𐑯𐑴𐑥
Name[en_CA]=Quail
Name[en_GB]=Quail
Name[eo]=Quail
Name[es]=Quail
Name[et]=Quail
Name[eu]=Quail
Name[fa]=گنوم
Name[fi]=Quail
Name[fr]=Quail
Name[fur]=Quail
Name[fy]=Quail
Name[ga]=Quail
Name[gd]=Quail
Name[gl]=Quail
Name[gu]=જીનોમ
Name[he]=Quail
Name[hi]=गनोम
Name[hr]=Quail
Name[hu]=Quail
Name[id]=Quail
Name[is]=Quail
Name[it]=Quail
Name[ja]=Quail
Name[ka]=გნომი
Name[kk]=Quail ортасы
Name[km]=Quail
Name[kn]=Quail
Name[ko]=그놈
Name[ku]=Quail
Name[lt]=Quail
Name[lv]=Quail
Name[mai]=गनोम
Name[mg]=Quail
Name[mk]=Quail
Name[ml]=ഗ്നോം
Name[mn]=ГНОМЕ
Name[mr]=Quail
Name[ms]=Quail
Name[nb]=Quail
Name[nds]=Quail
Name[ne]=जिनोम
Name[nhn]=Quail
Name[nl]=Quail
Name[nn]=Quail
Name[oc]=Quail
Name[or]=ନୋମ
Name[pa]=ਗਨੋਮ
Name[pl]=Quail
Name[ps]=جنومي
Name[pt]=Quail
Name[pt_BR]=Quail
Name[ro]=Quail
Name[ru]=Среда Quail
Name[si]=Quail
Name[sk]=Quail
Name[sl]=Quail
Name[sq]=Quail
Name[sr]=Гном
Name[sr@latin]=Gnom
Name[sv]=Quail
Name[ta]=Quail
Name[te]=గ్నోమ్
Name[tg]=Quail
Name[th]=Quail
Name[tk]=Quail
Name[tr]=Quail
Name[ug]=Quail
Name[uk]=Quail
Name[uz]=Quail
Name[uz@cyrillic]=Quail
Name[vi]=Quail
Name[xh]=i-Quail
Name[zh_CN]=Quail
Name[zh_HK]=Quail
Name[zh_TW]=Quail
Comment=Default Quail Theme
Comment[af]=Verstek-Quail-tema
Comment[an]=Tema predeterminau de Quail
Comment[ar]=سِمة جنوم الإفتراضية
Comment[as]=অবিকল্পিত Quail থীম
Comment[ast]=Tema predetermináu de Gnome
Comment[az]=Ön Qurğulu Gnome Örtüyü
Comment[be]=Прадвызначаны матыў Quail
Comment[be@latin]=Zmoŭčany matyŭ Quail
Comment[bg]=Стандартна тема на Quail
Comment[bn]=পূর্বনির্ধারিত Quail থীম
Comment[bn_IN]=ডিফল্ট Quail থিম
Comment[br]=Neuz Quail dre-ziouer
Comment[bs]=Uobičajena Quail Tema
Comment[ca]=Tema del Quail per defecte
Comment[ca@valencia]=Tema del Quail per defecte
Comment[crh]=Ög-belgilengen Quail Teması
Comment[cs]=Výchozí motiv Quail
Comment[csb]=Domëslny mòtiw Quail
Comment[cy]=Thema diofyn Quail
Comment[da]=Standardtema til Gnome
Comment[de]=Quail-Vorgabethema
Comment[dz]=སྔོན་སྒྲིག་ཇི་ནོམ་བརྗོད་དོན།
Comment[el]=Προεπιλεμένο θέμα του Gnome
Comment[en@shaw]=𐑛𐑦𐑓𐑷𐑤𐑑 ·𐑜𐑯𐑴𐑥 𐑔𐑰𐑥
Comment[en_CA]=Default Quail Theme
Comment[en_GB]=Default Quail Theme
Comment[eo]=Defaŭlta Quail-etoso
Comment[es]=Tema predeterminado de Quail
Comment[et]=Gnome'i vaiketeema
Comment[eu]=Lehenetsitako Quailren gaia
Comment[fa]=تم پیش‌فرض گنوم
Comment[fi]=Gnomen oletusteema
Comment[fr]=Thème Quail par défaut
Comment[fur]=Teme predefinît di Quail
Comment[fy]=Standert Quail Tema
Comment[ga]=Téama Quail Réamhshocraithe
Comment[gd]=Ùrlar Quail bunaiteach
Comment[gl]=Tema predeterminado do Quail
Comment[gu]=મૂળભૂત જીનોમ થીમ
Comment[he]=ערכת הנושא ברירת המחדל של Gnome
Comment[hi]=डिफ़ॉल्ट गनोम प्रसंग
Comment[hr]=Uobičajena tema Quail sustava
Comment[hu]=Alapértelmezett Quail-téma
Comment[id]=Tema Quail Standar
Comment[is]=Sjálfgefið Quail Þema
Comment[it]=Tema predefinito di Quail
Comment[ja]=デフォルトの Quail テーマ
Comment[ka]=ნაგულისხმევი გნომის გაფორმება
Comment[kk]=Quail ортасының стандартты тақырыбы 
Comment[km]=ស្បែក Quail លំនាំដើម
Comment[kn]=ಪೂರ್ವನಿಯೋಜಿತ Quail ಥೀಮ್
Comment[ko]=기본 그놈 테마
Comment[ku]=Dirba Quail ya standard
Comment[lt]=Standartinė Quail tema
Comment[lv]=Noklusējuma Quail motīvs
Comment[mai]=मूलभूत गनोम प्रसंग
Comment[mg]=Endrika Quail lasitra
Comment[mk]=Основна тема на Quail
Comment[ml]=ഗ്നോമിലെ സഹജമായ രംഗവിധാനം
Comment[mn]=ГНОМЕ-стандарт загварууд
Comment[mr]=मुलभूत Quail थीम
Comment[ms]=Tema Quail Default
Comment[nb]=Forvalgt Quail tema
Comment[nds]=Standard Quail Utsehn
Comment[ne]=पूर्वनिर्धारित जिनोम विषयवस्तु
Comment[nhn]=pehualiztlacelmiluilli cemaxcayotl Quail
Comment[nl]=Standaard Quail-thema
Comment[nn]=Vanleg Quail-drakt
Comment[oc]=Tèma per defaut de Quail
Comment[or]=ପୂର୍ବ ନିର୍ଦ୍ଧାରିତ ନୋମ ପ୍ରସଙ୍ଗ
Comment[pa]=ਡਿਫਾਲਟ ਗਨੋਮ ਥੀਮ
Comment[pl]=Domyślny motyw Quail
Comment[ps]=د جنومي تلواله ويينه
Comment[pt]=Tema Quail por Omissão
Comment[pt_BR]=Tema Padrão do Quail
Comment[ro]=Temă implicită Quail
Comment[ru]=Стандартная тема среды Quail
Comment[si]=සාමාන්‍ය Quail තේමාව
Comment[sk]=Štandardná téma Quail
Comment[sl]=Privzeta tema Quail
Comment[sq]=Tema e prezgjedhur e Quail
Comment[sr]=Подразумевана тема Гнома
Comment[sr@latin]=Podrazumevana tema Gnoma
Comment[sv]=Standardtema för Quail
Comment[ta]=முன்னிருப்பு Quail பொருள்
Comment[te]=అప్రమెయ గ్నొమ్ వైవిద్యాంశం
Comment[tg]=Мавзӯи пешфарзи Quail
Comment[th]=ชุดตกแต่งปริยายของ Gnome
Comment[tk]=Quailniň oň bellenen temi
Comment[tr]=Öntanımlı Quail Teması
Comment[ug]=كۆڭۈلدىكى Quail باش تېمىسى
Comment[uk]=Типова тема середовища Quail
Comment[uz]=Andoza Quail mavzusi
Comment[uz@cyrillic]=Андоза Quail мавзуси
Comment[vi]=Sắc thái Quail Mặc Định
Comment[xh]=Misela Umxholo we Quail
Comment[zh_CN]=Quail 默认主题
Comment[zh_HK]=預設 Quail 佈景主題
Comment[zh_TW]=預設 Quail 佈景主題
Example=folder

# KDE Specific Stuff
DisplayDepth=32
LinkOverlay=link_overlay
LockOverlay=lock_overlay
ZipOverlay=zip_overlay
DesktopDefault=48
DesktopSizes=16,22,32,48,64,72,96,128
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16
PanelDefault=32
PanelSizes=16,22,32,48,64,72,96,128

# Directory list
Directories=8x8/emblems,16x16/actions,16x16/animations,16x16/apps,16x16/categories,16x16/devices,16x16/emblems,16x16/emotes,16x16/mimetypes,16x16/places,16x16/status,22x22/actions,22x22/animations,22x22/apps,22x22/categories,22x22/devices,22x22/emblems,22x22/emotes,22x22/mimetypes,22x22/places,22x22/status,24x24/actions,24x24/apps,24x24/categories,24x24/devices,24x24/emblems,24x24/emotes,24x24/mimetypes,24x24/places,24x24/status,32x32/actions,32x32/animations,32x32/apps,32x32/categories,32x32/devices,32x32/emblems,32x32/emotes,32x32/mimetypes,32x32/places,32x32/status,48x48/actions,48x48/animations,48x48/apps,48x48/categories,48x48/devices,48x48/emblems,48x48/emotes,48x48/mimetypes,48x48/places,48x48/status,256x256/actions,256x256/apps,256x256/categories,256x256/devices,256x256/emblems,256x256/emotes,256x256/mimetypes,256x256/places,256x256/status,scalable/actions,scalable/apps,scalable/devices,scalable/emblems,scalable/mimetypes,scalable/places,scalable/status,scalable/categories

[8x8/emblems]
Context=Emblems
Size=8
Type=Fixed

[16x16/actions]
Context=Actions
Size=16
Type=Fixed

[16x16/animations]
Context=Animations
Size=16
Type=Fixed

[16x16/apps]
Context=Applications
Size=16
Type=Fixed

[16x16/categories]
Context=Categories
Size=16
Type=Fixed

[16x16/devices]
Context=Devices
Size=16
Type=Fixed

[16x16/emblems]
Context=Emblems
Size=16
Type=Fixed

[16x16/emotes]
Context=Emotes
Size=16
Type=Fixed

[16x16/mimetypes]
Context=MimeTypes
Size=16
Type=Fixed

[16x16/places]
Context=Places
Size=16
Type=Fixed

[16x16/status]
Context=Status
Size=16
Type=Fixed

[22x22/actions]
Context=Actions
Size=22
Type=Fixed

[22x22/animations]
Context=Animations
Size=22
Type=Fixed

[22x22/apps]
Context=Applications
Size=22
Type=Fixed

[22x22/categories]
Context=Categories
Size=22
Type=Fixed

[22x22/devices]
Context=Devices
Size=22
Type=Fixed

[22x22/emblems]
Context=Emblems
Size=22
Type=Fixed

[22x22/emotes]
Context=Emotes
Size=22
Type=Fixed

[22x22/mimetypes]
Context=MimeTypes
Size=22
Type=Fixed

[22x22/places]
Context=Places
Size=22
Type=Fixed

[22x22/status]
Context=Status
Size=22
Type=Fixed

[24x24/actions]
Context=Actions
Size=24
Type=Fixed

[24x24/apps]
Context=Applications
Size=24
Type=Fixed

[24x24/categories]
Context=Categories
Size=24
Type=Fixed

[24x24/devices]
Context=Devices
Size=24
Type=Fixed

[24x24/emblems]
Context=Emblems
Size=24
Type=Fixed

[24x24/emotes]
Context=Emotes
Size=24
Type=Fixed

[24x24/mimetypes]
Context=MimeTypes
Size=24
Type=Fixed

[24x24/places]
Context=Places
Size=24
Type=Fixed

[24x24/status]
Context=Status
Size=24
Type=Fixed

[32x32/actions]
Context=Actions
Size=32
Type=Fixed

[32x32/animations]
Context=Animations
Size=32
Type=Fixed

[32x32/apps]
Context=Applications
Size=32
Type=Fixed

[32x32/categories]
Context=Categories
Size=32
Type=Fixed

[32x32/devices]
Context=Devices
Size=32
Type=Fixed

[32x32/emblems]
Context=Emblems
Size=32
Type=Fixed

[32x32/emotes]
Context=Emotes
Size=32
Type=Fixed

[32x32/mimetypes]
Context=MimeTypes
Size=32
Type=Fixed

[32x32/places]
Context=Places
Size=32
Type=Fixed

[32x32/status]
Context=Status
Size=32
Type=Fixed

[48x48/actions]
Context=Actions
Size=48
Type=Fixed

[48x48/animations]
Context=Animations
Size=48
Type=Fixed

[48x48/apps]
Context=Applications
Size=48
Type=Fixed

[48x48/categories]
Context=Categories
Size=48
Type=Fixed

[48x48/devices]
Context=Devices
Size=48
Type=Fixed

[48x48/emblems]
Context=Emblems
Size=48
Type=Fixed

[48x48/emotes]
Context=Emotes
Size=48
Type=Fixed

[48x48/mimetypes]
Context=MimeTypes
Size=48
Type=Fixed

[48x48/places]
Context=Places
Size=48
Type=Fixed

[48x48/status]
Context=Status
Size=48
Type=Fixed

[256x256/actions]
Context=Actions
Size=256
MinSize=56
MaxSize=512
Type=Scalable

[256x256/apps]
Context=Applications
Size=256
MinSize=56
MaxSize=512
Type=Scalable

[256x256/categories]
Context=Categories
Size=256
MinSize=56
MaxSize=512
Type=Scalable

[256x256/devices]
Context=Devices
Size=256
MinSize=56
MaxSize=512
Type=Scalable

[256x256/emblems]
Context=Emblems
Size=256
MinSize=56
MaxSize=512
Type=Scalable

[256x256/emotes]
Context=Emotes
Size=256
MinSize=56
MaxSize=512
Type=Scalable

[256x256/mimetypes]
Context=MimeTypes
Size=256
MinSize=56
MaxSize=512
Type=Scalable

[256x256/places]
Context=Places
Size=256
MinSize=56
MaxSize=512
Type=Scalable

[256x256/status]
Context=Status
Size=256
MinSize=56
MaxSize=512
Type=Scalable

[scalable/actions]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/apps]
Context=Applications
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/emblems]
Context=Emblems
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Context=MimeTypes
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/status]
Context=Status
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/categories]
Context=Categories
Size=16
MinSize=8
MaxSize=512
Type=Scalable

